const $=s=>document.querySelector(s), firstStep=$('main > section').innerHTML;
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const iso=d=>`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`;
const dateOf=s=>new Date(s+'T12:00:00'),today=()=>iso(new Date()),arrow='<span aria-hidden="true">↗</span>';
const state={version:4,step:1,type:'project',name:'',cardCreated:false,source:'card',cardItem:'',newItem:'',date:today(),repeat:'once',planAdded:false,boardType:'note',note:'',photoName:'',boardLinked:true,boardAdded:false};
try{const prior=JSON.parse(localStorage.getItem('aurora-onboarding-live-v1')||'null');if(prior?.version===4){for(const k of Object.keys(state))if(typeof prior[k]===typeof state[k])state[k]=prior[k]}else if(prior){state.type=prior.type==='habit'?'habit':'project';state.name=String(prior.name||'').slice(0,45);state.cardItem=String(prior.item||'').slice(0,120);state.cardCreated=!!state.name;state.date=/^\d{4}-\d{2}-\d{2}$/.test(prior.date||'')?prior.date:today();state.step=prior.step>1?2:1;}}catch{}
if(![1,2,3,4].includes(state.step))state.step=1;
if(!['habit','project'].includes(state.type))state.type='project';
if(!['once','daily','weekly'].includes(state.repeat))state.repeat='once';
if(!/^\d{4}-\d{2}-\d{2}$/.test(state.date)||Number.isNaN(dateOf(state.date).getTime()))state.date=today();
let monthView=dateOf(state.date),photoURL='',photoBusy=false;
const colour=()=>state.type==='habit'?'#3fbf7f':'#6f8cff';
const item=()=>state.source==='card'?state.cardItem:state.newItem;
const linked=()=>state.source==='card'&&state.cardCreated;
const repeatLabel=()=>({once:'One time',daily:'Every day',weekly:'Every week'}[state.repeat]);
const readable=s=>dateOf(s).toLocaleDateString('en',{weekday:'short',month:'short',day:'numeric'});
function save(){try{localStorage.setItem('aurora-onboarding-live-v1',JSON.stringify(state))}catch{}}
function progress(n){return `<div class="kicker"><span class="progress" aria-hidden="true">${[1,2,3].map(i=>`<i class="${i<=n?'past':''}"></i>`).join('')}</span>${['','Your space','Your plan','Your board'][n]} · ${n} of 3</div>`}
function go(n){state.step=n;save();render();const heading=$('h1');heading.tabIndex=-1;heading.focus({preventScroll:true});window.scrollTo(0,0)}
function back(){return '<button class="back" id="back">← Back</button>'}
function cardHTML(){return `<article class="card ${state.type==='habit'?'habit-card':''}"><div class="card-type">${state.type==='habit'?'Habit':'Project'}</div><h2 id="card-name">${esc(state.name.trim()||(state.type==='habit'?'Your first habit':'Your first project'))}</h2><p>Keep your notes, moments<br>and plans together.</p><div class="card-bottom"><span>${state.type==='habit'?'Find a rhythm that feels like you':'A little room for your ideas'}</span>${arrow}</div></article><p class="preview-caption">Your space. Timing comes next, in Plan.</p>`}
function configureFooter(text,action,enabled=true){const next=$('#continue');next.hidden=false;next.innerHTML=esc(text)+arrow;next.disabled=!enabled;next.onclick=action;$('.footer-note').textContent='Yours from the start. No account needed.'}
function updateCard(){const h=$('#card-name');if(h)h.textContent=state.name.trim()||(state.type==='habit'?'Your first habit':'Your first project');$('#continue').disabled=!state.name.trim();save()}
function weekHTML(){const selected=dateOf(state.date),start=new Date(selected);start.setDate(start.getDate()-(start.getDay()+6)%7);return Array.from({length:7},(_,i)=>{const day=new Date(start);day.setDate(start.getDate()+i);const d=iso(day);return `<button class="plan-day ${d===state.date?'selected':''}" data-day="${d}" aria-label="${day.toLocaleDateString('en',{weekday:'long',month:'long',day:'numeric',year:'numeric'})}" aria-pressed="${d===state.date}"><span>${day.toLocaleDateString('en',{weekday:'short'})}</span><strong>${day.getDate()}</strong><i></i></button>`}).join('')}
function planHTML(){return `<section class="plan-preview" aria-label="Plan"><div class="plan-heading"><h2>Plan</h2><div class="week-nav"><button data-week="-1" aria-label="Previous week">‹</button><button id="month-open" aria-haspopup="dialog">${dateOf(state.date).toLocaleDateString('en',{month:'short',year:'numeric'})} ▾</button><button data-week="1" aria-label="Next week">›</button></div></div><div class="plan-week">${weekHTML()}</div><div class="plan-agenda"><h3>${readable(state.date)}</h3><div id="agenda-entry"></div></div><p class="connection-note" id="connection-note"></p></section>`}
function updateAgenda(){const entry=$('#agenda-entry');if(!entry)return;entry.innerHTML=item().trim()?`<div class="plan-event ${linked()?'linked':''}"><i class="plan-check" aria-hidden="true"></i><div><strong>${esc(item().trim())}</strong><span>${linked()?esc(state.name)+' · ':''}${repeatLabel()}</span></div></div>`:'<p class="empty-plan">A little room in your day.<br>Choose your card or add something new.</p>';$('#connection-note').textContent=linked()?'One item, in Plan and in your card.':'An independent item, here in Plan.';if(state.step===2)$('#continue').disabled=!item().trim();save()}
function bindPlan(){document.querySelectorAll('[data-day]').forEach(b=>b.onclick=()=>{state.date=b.dataset.day;monthView=dateOf(state.date);refreshPlan()});document.querySelectorAll('[data-week]').forEach(b=>b.onclick=()=>{const d=dateOf(state.date);d.setDate(d.getDate()+Number(b.dataset.week)*7);state.date=iso(d);monthView=d;refreshPlan()});$('#month-open').onclick=openCalendar;updateAgenda()}
function refreshPlan(){const active=document.activeElement?.dataset;const focusDay=active?.day,focusWeek=active?.week;$('.card-wrap').innerHTML=planHTML();bindPlan();if(focusDay)$(`[data-day="${state.date}"]`)?.focus({preventScroll:true});if(focusWeek)$(`[data-week="${focusWeek}"]`)?.focus({preventScroll:true})}
function openCalendar(){monthView=dateOf(state.date);let dialog=$('#calendar');if(!dialog){dialog=document.createElement('dialog');dialog.id='calendar';dialog.className='calendar-dialog';dialog.setAttribute('aria-labelledby','calendar-title');document.body.append(dialog);dialog.addEventListener('click',e=>{if(e.target===dialog){const r=dialog.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)dialog.close()}});dialog.onclose=()=>$('#month-open')?.focus({preventScroll:true})}drawCalendar();dialog.showModal();dialog.querySelector('.picked')?.focus({preventScroll:true})}
function drawCalendar(){const first=new Date(monthView.getFullYear(),monthView.getMonth(),1,12),start=new Date(first);start.setDate(1-(first.getDay()+6)%7);const days=Array.from({length:42},(_,i)=>{const d=new Date(start);d.setDate(start.getDate()+i);const key=iso(d);return `<button class="${d.getMonth()!==first.getMonth()?'outside ':''}${key===state.date?'picked':''}" data-calday="${key}" aria-label="${d.toLocaleDateString('en',{weekday:'long',month:'long',day:'numeric',year:'numeric'})}" ${key===state.date?'aria-current="date"':''}>${d.getDate()}</button>`}).join('');
 $('#calendar').innerHTML=`<div class="calendar-top"><button data-month="-1" aria-label="Previous month">‹</button><h2 id="calendar-title">${first.toLocaleDateString('en',{month:'long',year:'numeric'})}</h2><button data-month="1" aria-label="Next month">›</button></div><div class="month-grid">${['M','T','W','T','F','S','S'].map(d=>`<span aria-hidden="true">${d}</span>`).join('')}${days}</div><div class="calendar-bottom"><button id="cal-today">Today</button><button id="cal-close">Close</button></div>`;
 document.querySelectorAll('[data-month]').forEach(b=>b.onclick=()=>{monthView=new Date(monthView.getFullYear(),monthView.getMonth()+Number(b.dataset.month),1,12);drawCalendar();$(`[data-month="${b.dataset.month}"]`).focus()});document.querySelectorAll('[data-calday]').forEach(b=>b.onclick=()=>{state.date=b.dataset.calday;$('#calendar').close();refreshPlan();$('#month-open').focus({preventScroll:true})});$('#cal-today').onclick=()=>{state.date=today();$('#calendar').close();refreshPlan();$('#month-open').focus()};$('#cal-close').onclick=()=>$('#calendar').close();}
function boardSource(){return `<p class="preview-caption">${state.boardLinked&&state.cardCreated?'On Board, connected to '+esc(state.name)+'.':'On Board. A space for your moments.'}</p>`}
function boardHTML(){if(state.boardType==='photo'&&photoURL)return `<article class="board-photo"><img src="${photoURL}" alt="Your selected photo"><div class="photo-caption">${esc(state.note.trim()||'A moment worth keeping')}</div></article>${boardSource()}`;return `<article class="board-note"><span class="small-label">Note</span><p>${esc(state.note.trim()||'An idea, a place, a little thing you want to keep.').replace(/\n/g,'<br>')}</p><span class="note-tail">${state.boardLinked&&state.cardCreated?esc(state.name):'Your Board'}</span></article>${boardSource()}`}
function updateBoard(){if(state.step!==3)return;$('.card-wrap').innerHTML=boardHTML();$('#continue').disabled=photoBusy||!(state.note.trim()||(state.boardType==='photo'&&photoURL));save()}
async function photoStore(mode,blob){return new Promise((resolve,reject)=>{const req=indexedDB.open('aurora-onboarding-live-media-v1',1);req.onupgradeneeded=()=>req.result.createObjectStore('media');req.onerror=()=>reject(req.error);req.onsuccess=()=>{const db=req.result,tx=db.transaction('media',mode==='get'?'readonly':'readwrite'),store=tx.objectStore('media');const q=mode==='get'?store.get('photo'):mode==='delete'?store.delete('photo'):store.put(blob,'photo');tx.oncomplete=()=>{resolve(q.result);db.close()};tx.onerror=()=>{reject(tx.error);db.close()}}})}
async function selectPhoto(file){if(!file)return;const error=$('#photo-error');error.textContent='';if(!file.type.startsWith('image/')){error.textContent='Choose a photo to continue.';return}if(file.size>20*1024*1024){error.textContent='Choose a photo smaller than 20 MB.';return}photoBusy=true;updateBoard();const url=URL.createObjectURL(file);try{const img=new Image();img.src=url;await img.decode();await photoStore('put',file);if(photoURL)URL.revokeObjectURL(photoURL);photoURL=url;state.photoName=file.name;render()}catch{URL.revokeObjectURL(url);if($('#photo-error'))$('#photo-error').textContent='This photo could not be opened. Try a JPG, PNG or WebP.'}finally{photoBusy=false;updateBoard()}}
function finish(){state.boardAdded=!!(state.note.trim()||(state.boardType==='photo'&&photoURL));go(4)}
function render(){document.body.dataset.step=state.step;document.documentElement.style.setProperty('--accent',colour());$('.toast').hidden=true;const section=$('main > section'),aside=$('.card-wrap'),skip=$('#skip');$('#continue').hidden=false;
 skip.textContent=state.step===4?'Review setup':'Skip for now';skip.onclick=()=>{if(state.step===1){state.cardCreated=false;state.source='new';go(2)}else if(state.step===2){state.planAdded=false;go(3)}else if(state.step===3){state.boardAdded=false;go(4)}else go(1)};
 if(state.step===1){section.innerHTML=firstStep;$('.kicker').outerHTML=progress(1);$('#name').value=state.name;aside.innerHTML=cardHTML();$('#name').oninput=e=>{state.name=e.target.value;updateCard()};document.querySelectorAll('[data-type]').forEach(b=>{b.setAttribute('aria-pressed',String(state.type===b.dataset.type));b.onclick=()=>{state.type=b.dataset.type;save();render()}});configureFooter('Continue to Plan',()=>{if(!state.name.trim())return;state.name=state.name.trim();state.cardCreated=true;state.source='card';if(!state.cardItem.trim())state.cardItem=state.name;go(2)},!!state.name.trim());}
 else if(state.step===2){if(!state.cardCreated)state.source='new';section.innerHTML=`${back()}${progress(2)}<h1>Plan your day.</h1><p class="intro">Use your card, or start with something new.</p><div class="source-options" role="group" aria-label="Where to start">${state.cardCreated?`<button class="source-choice ${state.source==='card'?'on':''}" data-source="card" aria-pressed="${state.source==='card'}"><span class="source-label">From your ${state.type}</span><strong>${esc(state.name)}</strong></button>`:''}<button class="source-choice ${state.source==='new'?'on':''}" data-source="new" aria-pressed="${state.source==='new'}"><span class="source-label">A fresh start</span><strong>＋ Something new</strong></button></div><label class="field-label" for="item">${linked()?'What would you like to plan?':'Your new plan'}</label><div class="input-wrap"><i aria-hidden="true"></i><input id="item" maxlength="120" autocomplete="off" placeholder="A walk, a call, time for yourself…"></div><div class="repeat-options"><span class="field-label">How often?</span><div class="segments" role="group" aria-label="Repeat">${[['once','Just once'],['daily','Daily'],['weekly','Weekly']].map(([id,label])=>`<button data-repeat="${id}" aria-pressed="${state.repeat===id}" class="${state.repeat===id?'on':''}">${label}</button>`).join('')}</div></div><p class="hint">Choose a day in Plan. You can change it anytime.</p>`;
 $('#back').onclick=()=>go(1);$('#item').value=item();$('#item').oninput=e=>{state[state.source==='card'?'cardItem':'newItem']=e.target.value;updateAgenda()};document.querySelectorAll('[data-source]').forEach(b=>b.onclick=()=>{state.source=b.dataset.source;save();render()});document.querySelectorAll('[data-repeat]').forEach(b=>b.onclick=()=>{state.repeat=b.dataset.repeat;document.querySelectorAll('[data-repeat]').forEach(x=>{x.classList.toggle('on',x===b);x.setAttribute('aria-pressed',String(x===b))});updateAgenda()});aside.innerHTML=planHTML();configureFooter('Continue to Board',()=>{if(!item().trim())return;state.planAdded=true;go(3)},!!item().trim());bindPlan();}
 else if(state.step===3){section.innerHTML=`${back()}${progress(3)}<h1>Keep a little<br>of your world.</h1><p class="intro">A photo, an idea, something worth keeping.<br>Give it a place on your Board.</p><div class="segments board-types" role="group" aria-label="Moment type"><button data-kind="note" class="${state.boardType==='note'?'on':''}" aria-pressed="${state.boardType==='note'}">Note</button><button data-kind="photo" class="${state.boardType==='photo'?'on':''}" aria-pressed="${state.boardType==='photo'}">Photo</button></div>${state.boardType==='photo'?`<label class="upload-button" for="photo-input">${photoURL?'Change photo':'＋ Choose a photo'}</label><input class="sr-only" id="photo-input" type="file" accept="image/*">${photoURL?'<button class="remove-photo" id="remove-photo">Remove photo</button>':''}<p class="field-error" id="photo-error" role="alert"></p>`:''}<label class="field-label" for="note">${state.boardType==='photo'?'A few words (optional)':'Your note'}</label><textarea id="note" rows="3" maxlength="600" placeholder="A place to visit. An idea to return to…"></textarea>${state.cardCreated?`<label class="link-row"><input id="board-linked" type="checkbox" ${state.boardLinked?'checked':''}><span>Connect to <strong>${esc(state.name)}</strong></span></label>`:''}<p class="hint">It can belong to a card, or just live on Board.</p>`;
 $('#back').onclick=()=>go(2);$('#note').value=state.note;$('#note').oninput=e=>{state.note=e.target.value;updateBoard()};document.querySelectorAll('[data-kind]').forEach(b=>b.onclick=()=>{state.boardType=b.dataset.kind;save();render()});if($('#board-linked'))$('#board-linked').onchange=e=>{state.boardLinked=e.target.checked;updateBoard()};if($('#photo-input'))$('#photo-input').onchange=e=>selectPhoto(e.target.files[0]);if($('#remove-photo'))$('#remove-photo').onclick=async()=>{await photoStore('delete');URL.revokeObjectURL(photoURL);photoURL='';state.photoName='';save();render()};configureFooter('Finish setup',finish,false);updateBoard();}
 else{section.innerHTML=`<div class="kicker">A little beginning. All yours.</div><h1>You’re ready.</h1><p class="intro">Your space, your plans, your moments.<br>Connected, in your own rhythm.</p><div class="setup-summary">${state.cardCreated?`<div><span>Spaces</span><strong>${esc(state.name)}</strong></div>`:'<div><span>Spaces</span><strong>Room for your first card</strong></div>'}${state.planAdded?`<div><span>Plan · ${readable(state.date)}</span><strong>${esc(item())}</strong><small>${repeatLabel()}${linked()?' · '+esc(state.name):''}</small></div>`:'<div><span>Plan</span><strong>Your day is open</strong></div>'}${state.boardAdded?`<div><span>Board${state.boardLinked&&state.cardCreated?' · '+esc(state.name):''}</span><strong>${esc(state.note.trim()||(state.boardType==='photo'?state.photoName:'Your first moment'))}</strong></div>`:'<div><span>Board</span><strong>A place for your first moment</strong></div>'}</div>`;aside.innerHTML=state.boardAdded?boardHTML():state.cardCreated?cardHTML():'<div class="empty-finish">A little room<br>for what matters.</div>';configureFooter('Open Aurora',openAurora,true);$('.footer-note').textContent='Everything you created will be waiting inside.';}
 save();}
async function boot(){render();try{const file=await photoStore('get');if(file)photoURL=URL.createObjectURL(file);else state.photoName=''}catch{state.photoName=''}render()}
let finishPending=false;
async function openAurora(){
 if(finishPending)return;finishPending=true;const button=$('#continue');button.disabled=true;button.textContent='Saving your space…';
 try{const photo=state.boardAdded&&state.boardType==='photo'?await photoStore('get'):null;parent.postMessage({type:'aurora:finish-setup',state:structuredClone(state),photo},location.origin)}
 catch{finishPending=false;button.disabled=false;button.textContent='Try again';$('.footer-note').textContent='Could not read your photo. Please try again.'}
}
window.addEventListener('message',e=>{if(e.origin!==location.origin||e.source!==parent)return;
 if(e.data?.type==='aurora:setup-saved'){try{localStorage.removeItem('aurora-onboarding-live-v1')}catch{}photoStore('delete').catch(()=>{});}
 if(e.data?.type==='aurora:setup-error'){finishPending=false;$('#continue').disabled=false;$('#continue').textContent='Open Aurora ↗';$('.footer-note').textContent=e.data.message;}
});

boot();
