const $=s=>document.querySelector(s), firstStep=$('main > section').innerHTML;
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const iso=d=>`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`;
const dateOf=s=>new Date(s+'T12:00:00'),today=()=>iso(new Date()),arrow='<span aria-hidden="true">↗</span>';
const state={version:4,step:1,type:'project',name:'',cardCreated:false,source:'card',cardItem:'',newItem:'',date:today(),repeat:'once',planAdded:false,boardType:'note',note:'',photoName:'',boardLinked:true,boardAdded:false};
try{const prior=JSON.parse(localStorage.getItem('aurora-onboarding-live-v1')||'null');if(prior?.version===4){for(const k of Object.keys(state))if(typeof prior[k]===typeof state[k])state[k]=prior[k]}else if(prior){state.type=prior.type==='habit'?'habit':'project';state.name=String(prior.name||'').slice(0,45);state.cardItem=String(prior.item||'').slice(0,120);state.cardCreated=!!state.name;state.date=/^\d{4}-\d{2}-\d{2}$/.test(prior.date||'')?prior.date:today();state.step=prior.step>1?2:1;}}catch{}
if(![1,2,3,4].includes(state.step))state.step=1;
if(!['habit','project'].includes(state.type))state.type='project';
if(!['once','daily','weekly'].includes(state.repeat))state.repeat='once';
if(!/^\d{4}-\d{2}-\d{2}$/.test(state.date)||Number.isNaN(dateOf(state.date).getTime()))state.date=today();
let monthView=dateOf(state.date),photoURL='',photoBusy=false;
const colour=()=>state.type==='habit'?'#3fbf7f':'#6f8cff';
const item=()=>state.source==='card'?state.cardItem:state.newItem;
const linked=()=>state.source==='card'&&state.cardCreated;
const repeatLabel=()=>({once:'Jednorázově',daily:'Každý den',weekly:'Každý týden'}[state.repeat]);
const readable=s=>dateOf(s).toLocaleDateString('cs',{weekday:'short',month:'short',day:'numeric'});
function save(){try{localStorage.setItem('aurora-onboarding-live-v1',JSON.stringify(state))}catch{}}
function progress(n){return `<div class="kicker"><span class="progress" aria-hidden="true">${[1,2,3].map(i=>`<i class="${i<=n?'past':''}"></i>`).join('')}</span>${['','Tvůj prostor','Tvůj plán','Tvoje nástěnka'][n]} · ${n} ze 3</div>`}
function go(n){state.step=n;save();render();const heading=$('h1');heading.tabIndex=-1;heading.focus({preventScroll:true});window.scrollTo(0,0)}
function back(){return '<button class="back" id="back">← Zpět</button>'}
function cardHTML(){return `<article class="card ${state.type==='habit'?'habit-card':''}"><div class="card-type">${state.type==='habit'?'Návyk':'Projekt'}</div><h2 id="card-name">${esc(state.name.trim()||(state.type==='habit'?'Tvůj první návyk':'Tvůj první projekt'))}</h2><p>Poznámky, momenty<br>a plány pohromadě.</p><div class="card-bottom"><span>${state.type==='habit'?'Najdi rytmus, který ti sedí':'Místo pro tvoje nápady'}</span>${arrow}</div></article><p class="preview-caption">Tvůj prostor. Čas přijde na řadu v Plánu.</p>`}
function configureFooter(text,action,enabled=true){const next=$('#continue');next.hidden=false;next.innerHTML=esc(text)+arrow;next.disabled=!enabled;next.onclick=action;$('.footer-note').textContent='Tvoje od začátku. Účet není potřeba.'}
function updateCard(){const h=$('#card-name');if(h)h.textContent=state.name.trim()||(state.type==='habit'?'Tvůj první návyk':'Tvůj první projekt');$('#continue').disabled=!state.name.trim();save()}
function weekHTML(){const selected=dateOf(state.date),start=new Date(selected);start.setDate(start.getDate()-(start.getDay()+6)%7);return Array.from({length:7},(_,i)=>{const day=new Date(start);day.setDate(start.getDate()+i);const d=iso(day);return `<button class="plan-day ${d===state.date?'selected':''}" data-day="${d}" aria-label="${day.toLocaleDateString('cs',{weekday:'long',month:'long',day:'numeric',year:'numeric'})}" aria-pressed="${d===state.date}"><span>${day.toLocaleDateString('cs',{weekday:'short'})}</span><strong>${day.getDate()}</strong><i></i></button>`}).join('')}
function planHTML(){return `<section class="plan-preview" aria-label="Plán"><div class="plan-heading"><h2>Plán</h2><div class="week-nav"><button data-week="-1" aria-label="Předchozí týden">‹</button><button id="month-open" aria-haspopup="dialog">${dateOf(state.date).toLocaleDateString('cs',{month:'short',year:'numeric'})} ▾</button><button data-week="1" aria-label="Další týden">›</button></div></div><div class="plan-week">${weekHTML()}</div><div class="plan-agenda"><h3>${readable(state.date)}</h3><div id="agenda-entry"></div></div><p class="connection-note" id="connection-note"></p></section>`}
function updateAgenda(){const entry=$('#agenda-entry');if(!entry)return;entry.innerHTML=item().trim()?`<div class="plan-event ${linked()?'linked':''}"><i class="plan-check" aria-hidden="true"></i><div><strong>${esc(item().trim())}</strong><span>${linked()?esc(state.name)+' · ':''}${repeatLabel()}</span></div></div>`:'<p class="empty-plan">Trocha místa ve tvém dni.<br>Vyber kartu nebo přidej něco nového.</p>';$('#connection-note').textContent=linked()?'Jedna položka, v Plánu i na kartě.':'Samostatná položka v Plánu.';if(state.step===2)$('#continue').disabled=!item().trim();save()}
function bindPlan(){document.querySelectorAll('[data-day]').forEach(b=>b.onclick=()=>{state.date=b.dataset.day;monthView=dateOf(state.date);refreshPlan()});document.querySelectorAll('[data-week]').forEach(b=>b.onclick=()=>{const d=dateOf(state.date);d.setDate(d.getDate()+Number(b.dataset.week)*7);state.date=iso(d);monthView=d;refreshPlan()});$('#month-open').onclick=openCalendar;updateAgenda()}
function refreshPlan(){const active=document.activeElement?.dataset;const focusDay=active?.day,focusWeek=active?.week;$('.card-wrap').innerHTML=planHTML();bindPlan();if(focusDay)$(`[data-day="${state.date}"]`)?.focus({preventScroll:true});if(focusWeek)$(`[data-week="${focusWeek}"]`)?.focus({preventScroll:true})}
function openCalendar(){monthView=dateOf(state.date);let dialog=$('#calendar');if(!dialog){dialog=document.createElement('dialog');dialog.id='calendar';dialog.className='calendar-dialog';dialog.setAttribute('aria-labelledby','calendar-title');document.body.append(dialog);dialog.addEventListener('click',e=>{if(e.target===dialog){const r=dialog.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)dialog.close()}});dialog.onclose=()=>$('#month-open')?.focus({preventScroll:true})}drawCalendar();dialog.showModal();dialog.querySelector('.picked')?.focus({preventScroll:true})}
function drawCalendar(){const first=new Date(monthView.getFullYear(),monthView.getMonth(),1,12),start=new Date(first);start.setDate(1-(first.getDay()+6)%7);const days=Array.from({length:42},(_,i)=>{const d=new Date(start);d.setDate(start.getDate()+i);const key=iso(d);return `<button class="${d.getMonth()!==first.getMonth()?'outside ':''}${key===state.date?'picked':''}" data-calday="${key}" aria-label="${d.toLocaleDateString('cs',{weekday:'long',month:'long',day:'numeric',year:'numeric'})}" ${key===state.date?'aria-current="date"':''}>${d.getDate()}</button>`}).join('');
 $('#calendar').innerHTML=`<div class="calendar-top"><button data-month="-1" aria-label="Předchozí měsíc">‹</button><h2 id="calendar-title">${first.toLocaleDateString('cs',{month:'long',year:'numeric'})}</h2><button data-month="1" aria-label="Další měsíc">›</button></div><div class="month-grid">${['P','Ú','S','Č','P','S','N'].map(d=>`<span aria-hidden="true">${d}</span>`).join('')}${days}</div><div class="calendar-bottom"><button id="cal-today">Dnes</button><button id="cal-close">Zavřít</button></div>`;
 document.querySelectorAll('[data-month]').forEach(b=>b.onclick=()=>{monthView=new Date(monthView.getFullYear(),monthView.getMonth()+Number(b.dataset.month),1,12);drawCalendar();$(`[data-month="${b.dataset.month}"]`).focus()});document.querySelectorAll('[data-calday]').forEach(b=>b.onclick=()=>{state.date=b.dataset.calday;$('#calendar').close();refreshPlan();$('#month-open').focus({preventScroll:true})});$('#cal-today').onclick=()=>{state.date=today();$('#calendar').close();refreshPlan();$('#month-open').focus()};$('#cal-close').onclick=()=>$('#calendar').close();}
function boardSource(){return `<p class="preview-caption">${state.boardLinked&&state.cardCreated?'Na Nástěnce, propojeno s '+esc(state.name)+'.':'Na Nástěnce. Místo pro tvoje momenty.'}</p>`}
function boardHTML(){if(state.boardType==='photo'&&photoURL)return `<article class="board-photo"><img src="${photoURL}" alt="Tvoje vybraná fotka"><div class="photo-caption">${esc(state.note.trim()||'Moment, který stojí za uchování')}</div></article>${boardSource()}`;return `<article class="board-note"><span class="small-label">Poznámka</span><p>${esc(state.note.trim()||'Nápad, místo, drobnost, kterou si chceš uchovat.').replace(/\n/g,'<br>')}</p><span class="note-tail">${state.boardLinked&&state.cardCreated?esc(state.name):'Tvoje nástěnka'}</span></article>${boardSource()}`}
function updateBoard(){if(state.step!==3)return;$('.card-wrap').innerHTML=boardHTML();$('#continue').disabled=photoBusy||!(state.note.trim()||(state.boardType==='photo'&&photoURL));save()}
async function photoStore(mode,blob){return new Promise((resolve,reject)=>{const req=indexedDB.open('aurora-onboarding-live-media-v1',1);req.onupgradeneeded=()=>req.result.createObjectStore('media');req.onerror=()=>reject(req.error);req.onsuccess=()=>{const db=req.result,tx=db.transaction('media',mode==='get'?'readonly':'readwrite'),store=tx.objectStore('media');const q=mode==='get'?store.get('photo'):mode==='delete'?store.delete('photo'):store.put(blob,'photo');tx.oncomplete=()=>{resolve(q.result);db.close()};tx.onerror=()=>{reject(tx.error);db.close()}}})}
async function selectPhoto(file){if(!file)return;const error=$('#photo-error');error.textContent='';if(!file.type.startsWith('image/')){error.textContent='Pro pokračování vyber fotku.';return}if(file.size>20*1024*1024){error.textContent='Vyber fotku menší než 20 MB.';return}photoBusy=true;updateBoard();const url=URL.createObjectURL(file);try{const img=new Image();img.src=url;await img.decode();await photoStore('put',file);if(photoURL)URL.revokeObjectURL(photoURL);photoURL=url;state.photoName=file.name;render()}catch{URL.revokeObjectURL(url);if($('#photo-error'))$('#photo-error').textContent='Fotku nelze otevřít. Zkus JPG, PNG nebo WebP.'}finally{photoBusy=false;updateBoard()}}
function finish(){state.boardAdded=!!(state.note.trim()||(state.boardType==='photo'&&photoURL));go(4)}
function render(){document.body.dataset.step=state.step;document.documentElement.style.setProperty('--accent',colour());$('.toast').hidden=true;const section=$('main > section'),aside=$('.card-wrap'),skip=$('#skip');$('#continue').hidden=false;
 skip.textContent=state.step===4?'Projít nastavení':'Zatím přeskočit';skip.onclick=()=>{if(state.step===1){state.cardCreated=false;state.source='new';go(2)}else if(state.step===2){state.planAdded=false;go(3)}else if(state.step===3){state.boardAdded=false;go(4)}else go(1)};
 if(state.step===1){section.innerHTML=firstStep;$('.kicker').outerHTML=progress(1);$('#name').value=state.name;aside.innerHTML=cardHTML();$('#name').oninput=e=>{state.name=e.target.value;updateCard()};document.querySelectorAll('[data-type]').forEach(b=>{b.setAttribute('aria-pressed',String(state.type===b.dataset.type));b.onclick=()=>{state.type=b.dataset.type;save();render()}});configureFooter('Pokračovat do Plánu',()=>{if(!state.name.trim())return;state.name=state.name.trim();state.cardCreated=true;state.source='card';if(!state.cardItem.trim())state.cardItem=state.name;go(2)},!!state.name.trim());}
 else if(state.step===2){if(!state.cardCreated)state.source='new';section.innerHTML=`${back()}${progress(2)}<h1>Naplánuj si den.</h1><p class="intro">Použij svoji kartu nebo začni něčím novým.</p><div class="source-options" role="group" aria-label="Čím začít">${state.cardCreated?`<button class="source-choice ${state.source==='card'?'on':''}" data-source="card" aria-pressed="${state.source==='card'}"><span class="source-label">Z tvé karty: ${state.type==='habit'?'návyk':'projekt'}</span><strong>${esc(state.name)}</strong></button>`:''}<button class="source-choice ${state.source==='new'?'on':''}" data-source="new" aria-pressed="${state.source==='new'}"><span class="source-label">Nový začátek</span><strong>＋ Něco nového</strong></button></div><label class="field-label" for="item">${linked()?'Co si chceš naplánovat?':'Tvůj nový plán'}</label><div class="input-wrap"><i aria-hidden="true"></i><input id="item" maxlength="120" autocomplete="off" placeholder="Procházka, hovor, čas pro sebe…"></div><div class="repeat-options"><span class="field-label">Jak často?</span><div class="segments" role="group" aria-label="Opakování">${[['once','Jen jednou'],['daily','Denně'],['weekly','Týdně']].map(([id,label])=>`<button data-repeat="${id}" aria-pressed="${state.repeat===id}" class="${state.repeat===id?'on':''}">${label}</button>`).join('')}</div></div><p class="hint">Vyber den v Plánu. Kdykoli ho můžeš změnit.</p>`;
 $('#back').onclick=()=>go(1);$('#item').value=item();$('#item').oninput=e=>{state[state.source==='card'?'cardItem':'newItem']=e.target.value;updateAgenda()};document.querySelectorAll('[data-source]').forEach(b=>b.onclick=()=>{state.source=b.dataset.source;save();render()});document.querySelectorAll('[data-repeat]').forEach(b=>b.onclick=()=>{state.repeat=b.dataset.repeat;document.querySelectorAll('[data-repeat]').forEach(x=>{x.classList.toggle('on',x===b);x.setAttribute('aria-pressed',String(x===b))});updateAgenda()});aside.innerHTML=planHTML();configureFooter('Pokračovat na Nástěnku',()=>{if(!item().trim())return;state.planAdded=true;go(3)},!!item().trim());bindPlan();}
 else if(state.step===3){section.innerHTML=`${back()}${progress(3)}<h1>Uchovej si kousek<br>svého světa.</h1><p class="intro">Fotka, nápad, něco, co si chceš uchovat.<br>Dej tomu místo na Nástěnce.</p><div class="segments board-types" role="group" aria-label="Typ momentu"><button data-kind="note" class="${state.boardType==='note'?'on':''}" aria-pressed="${state.boardType==='note'}">Poznámka</button><button data-kind="photo" class="${state.boardType==='photo'?'on':''}" aria-pressed="${state.boardType==='photo'}">Fotka</button></div>${state.boardType==='photo'?`<label class="upload-button" for="photo-input">${photoURL?'Změnit fotku':'＋ Vybrat fotku'}</label><input class="sr-only" id="photo-input" type="file" accept="image/*">${photoURL?'<button class="remove-photo" id="remove-photo">Odebrat fotku</button>':''}<p class="field-error" id="photo-error" role="alert"></p>`:''}<label class="field-label" for="note">${state.boardType==='photo'?'Pár slov (nepovinné)':'Tvoje poznámka'}</label><textarea id="note" rows="3" maxlength="600" placeholder="Místo k návštěvě. Nápad, ke kterému se vrátit…"></textarea>${state.cardCreated?`<label class="link-row"><input id="board-linked" type="checkbox" ${state.boardLinked?'checked':''}><span>Propojit s <strong>${esc(state.name)}</strong></span></label>`:''}<p class="hint">Může patřit ke kartě nebo žít samostatně na Nástěnce.</p>`;
 $('#back').onclick=()=>go(2);$('#note').value=state.note;$('#note').oninput=e=>{state.note=e.target.value;updateBoard()};document.querySelectorAll('[data-kind]').forEach(b=>b.onclick=()=>{state.boardType=b.dataset.kind;save();render()});if($('#board-linked'))$('#board-linked').onchange=e=>{state.boardLinked=e.target.checked;updateBoard()};if($('#photo-input'))$('#photo-input').onchange=e=>selectPhoto(e.target.files[0]);if($('#remove-photo'))$('#remove-photo').onclick=async()=>{await photoStore('delete');URL.revokeObjectURL(photoURL);photoURL='';state.photoName='';save();render()};configureFooter('Dokončit nastavení',finish,false);updateBoard();}
 else{section.innerHTML=`<div class="kicker">Malý začátek. Celý tvůj.</div><h1>Máš hotovo.</h1><p class="intro">Tvůj prostor, tvoje plány, tvoje momenty.<br>Propojené, ve tvém rytmu.</p><div class="setup-summary">${state.cardCreated?`<div><span>Prostory</span><strong>${esc(state.name)}</strong></div>`:'<div><span>Prostory</span><strong>Místo pro tvoji první kartu</strong></div>'}${state.planAdded?`<div><span>Plán · ${readable(state.date)}</span><strong>${esc(item())}</strong><small>${repeatLabel()}${linked()?' · '+esc(state.name):''}</small></div>`:'<div><span>Plán</span><strong>Tvůj den je volný</strong></div>'}${state.boardAdded?`<div><span>Nástěnka${state.boardLinked&&state.cardCreated?' · '+esc(state.name):''}</span><strong>${esc(state.note.trim()||(state.boardType==='photo'?state.photoName:'Tvůj první moment'))}</strong></div>`:'<div><span>Nástěnka</span><strong>Místo pro tvůj první moment</strong></div>'}</div>`;aside.innerHTML=state.boardAdded?boardHTML():state.cardCreated?cardHTML():'<div class="empty-finish">Místo pro to,<br>na čem záleží.</div>';configureFooter('Otevřít Auroru',openAurora,true);$('.footer-note').textContent='Všechno, co jsi vytvořil, na tebe čeká uvnitř.';}
 save();}
async function boot(){render();try{const file=await photoStore('get');if(file)photoURL=URL.createObjectURL(file);else state.photoName=''}catch{state.photoName=''}render()}
let finishPending=false;
// Only compress for an actual keyboard resize, not a phone held landscape.
let setupHeight=innerHeight,setupWidth=innerWidth;
function fitSetupKeyboard(){if(Math.abs(innerWidth-setupWidth)>80){setupWidth=innerWidth;setupHeight=innerHeight;}
 setupHeight=Math.max(setupHeight,innerHeight);
 document.body.classList.toggle('keyboard-open',setupHeight-innerHeight>120&&!!document.activeElement?.matches('input:not([type=checkbox]),textarea'));
}
window.addEventListener('resize',fitSetupKeyboard);document.addEventListener('focusin',fitSetupKeyboard);document.addEventListener('focusout',()=>setTimeout(fitSetupKeyboard,0));
function pinSetup(){
 const focused=!!document.activeElement?.matches('input:not([type=checkbox]):not([type=radio]):not([type=file]),textarea');
 if(scrollX||scrollY)window.scrollTo({left:0,top:0,behavior:'instant'});
 if(parent!==window)parent.postMessage({type:'aurora:input-focus',focused},location.origin);
}
document.addEventListener('focusin',pinSetup);document.addEventListener('focusout',()=>setTimeout(pinSetup,0));
window.addEventListener('scroll',pinSetup,{passive:true});window.addEventListener('resize',pinSetup);
async function openAurora(){
 if(finishPending)return;finishPending=true;const button=$('#continue');button.disabled=true;button.textContent='Ukládám tvůj prostor…';
 try{const photo=state.boardAdded&&state.boardType==='photo'?await photoStore('get'):null;parent.postMessage({type:'aurora:finish-setup',state:structuredClone(state),photo},location.origin)}
 catch{finishPending=false;button.disabled=false;button.textContent='Zkusit znovu';$('.footer-note').textContent='Fotku nelze načíst. Zkus to znovu.'}
}
window.addEventListener('message',e=>{if(e.origin!==location.origin||e.source!==parent)return;
 if(e.data?.type==='aurora:setup-saved'){try{localStorage.removeItem('aurora-onboarding-live-v1')}catch{}photoStore('delete').catch(()=>{});}
 if(e.data?.type==='aurora:setup-error'){finishPending=false;$('#continue').disabled=false;$('#continue').textContent='Otevřít Auroru ↗';$('.footer-note').textContent=e.data.message;}
});

boot();
